チューニング空間を数値で指定できるように追加しました。
kanreisa/Mirakurun pull request #15
Opened 2017-01-30 13:12 UTC by eru01

BonRecTest等をチューナーとして設定する際、
`bonrectest --driver hoge --channel <channel> **--space <space>** ~~`
としてチューニング空間を指定できるようにしました。
channels.ymlで`space: [0-9]+`とすることで流し込まれます。

channelsで未指定、かつチューナーに<space>があった場合は0として処理されます。

2017-01-30 14:53 UTC, kanreisa requested changes
加えて、こちらのファイルの変更もお願いいたします。

* https://github.com/eru01/Mirakurun/blob/c421a93fcf56dca4d08bdd8fac6f65e3a25df90d/api.yml#L67-L84
* https://github.com/eru01/Mirakurun/blob/c421a93fcf56dca4d08bdd8fac6f65e3a25df90d/api.d.ts#L41-L47

2017-01-30 14:53 UTC, kanreisa commented on doc/Configuration.md
> +  space: 0 # Tuning space number, which replaces <space> in tuner command (as integer; set to 0 if isn't specified)
コメントがちょっと長いので、
```
# integer: <space> as tuning space number in tuner command (default: 0)
```
こうかな？

2017-01-30 14:53 UTC, kanreisa commented on src/Mirakurun/TunerDevice.ts
> +            cmd = cmd.replace("<space>", ch.space.toString());
`ch.space.toString(10)` でお願いいたします m(_ _)m

2017-01-30 22:27 UTC, eru01 commented
レビューありがとうございます。
指摘事項反映しましたので、再チェックをお願いいたします。

2017-01-31 03:09 UTC, kanreisa requested changes

2017-01-31 03:09 UTC, kanreisa commented on api.d.ts
> +
謎の空行

2017-01-31 03:23 UTC, eru01 commented on api.d.ts
> +
編集ミスでした。訂正しました。

2017-01-31 03:37 UTC, merged

2017-01-31 03:39 UTC, kanreisa commented
github 上のエディタでの編集はお控えいただけると大変助かります。
PR ありがとうございました！

2017-01-31 04:05 UTC, eru01 commented
出先だったのでwebでやってしまいました、すみません。
マージありがとうございました :-)