PAT CRC 比較処理の修正
kanreisa/Mirakurun pull request #53
Opened 2019-04-05 19:39 UTC by k-uraki

#51 の動作確認中に気になった動作の修正です。

PAT の CRC が不自然に変化してしまい、PAT のイベントが異常な頻度で発生し続けることがありました。

- 特に、サービスを制限している場合に顕著
- 前回比較時に `_patCRC` を保存した後、 0xFFFFFFFF となっていることが多い
  - サービス制限による PAT 書き換えで埋めた 0xFF ？
  - `Buffer.slice` で参照していたメモリ領域が上書きされた影響？

試しに `_patCRC` に値をコピーするように修正したところ、期待通りの動作をしているように見えます。
問題ないかご確認いただけますでしょうか。

2019-04-05 20:21 UTC, kanreisa requested changes

2019-04-05 20:21 UTC, kanreisa commented on src/Mirakurun/TSFilter.ts
> -            this._patCRC = packet.slice(packet[7] + 4, packet[7] + 8);
```
this._patCRC = Buffer.from(packet.slice(packet[7] + 4, packet[7] + 8));
```
のほうがよさそうな気がしますがどうでしょう？

2019-04-06 02:16 UTC, k-uraki commented on src/Mirakurun/TSFilter.ts
> -            this._patCRC = packet.slice(packet[7] + 4, packet[7] + 8);
ご提示のコードの方がシンプルで良いと思います！
修正しました。
(alloc の回数を減らそうとしたのですが、実行回数等を考慮するとあまり意味はなさそうです)

2019-04-06 17:14 UTC, kanreisa approved these changes

2019-04-08 08:56 UTC, merged