Programクラスのパフォーマンス改善
kanreisa/Mirakurun pull request #55
Opened 2019-04-26 11:43 UTC by masnagam

`get`および`exists`メソッドの計算量をO(N)からO(1)に改善．

これにより，以下のパフォーマンスが改善します．

* 起動時の`program.json`の読み込み時間
* `findByNetworkIdAndReplace`のブロック時間

`add`のたびに，`_item`を線形検索していましたが，ほとんどの場合IDがマッチすることはないのでかなりの時間を消費していました．

この修正により，`findByNetworkIdAndReplace`のブロック時間は問題にならない程度に速くなったので（Rock64でも１秒以下），`findByNetworkIdAndReplace`の非同期化は不要となりました．そのため，`async`および`await`のみ削除しました．

コメントにあるように，`_items`を`_itemMap`に置き換えてしまうことも可能でしたが，そうしてしまうと，Programクラスの大部分を書き換えることになるため，置き換えはしませんでした．置き換えることで，`splice`しなくて良くなるのでもう少し速くなるかもしれませんが，すでに十分速くなっているので，必要性は低いと考えています．

`_items`と`_itemMap`という似たものが２つあるのはよくないということでしたら，`_items`を削除しますので，指摘をお願いします．

2019-04-26 12:36 UTC, masnagam commented
ちなみに，この修正は #56 とは無関係です（多分．．）

2019-05-03 08:59 UTC, kanreisa commented
対応が遅くなりました。

`_itemMap` なのですが、[Map](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Map) はいかがでしょうか？
Map 使った上で、もしパフォーマンス問題なさそうであれば、_items を消してしまってもよいと思います。

2019-05-03 16:42 UTC, masnagam commented
`_items`を削除するかどうかは，パフォーマンスの良し悪しで判断するのではなく，修正による影響を考慮した上で判断すべきだと考えます．

書き換えてもいいのですが，以下について問題がないか判断をお願いします．

* 最初のコメントにも書きましたが，`_items`を現在の`Array`から`Object`または`Map`に置き換えた場合，`Program.ts`を大幅に書き換えることになります
  * 恐らく，diffを確認する意味がなくなります
* `Program.all()`の動作が変わります
  * 連想配列からプログラム一覧を取得するので，毎回違うJS Objectが返されますし，要素の順番も保証されません
  * 上記のように`Program.all()`の動作が変わると，問題が発生するようなコードはないですか？

問題ないのであれば書き換えます．

`Object`も`Map`もV8ではハッシュテーブルのようなものを使って実装されているようです．つまり，要素数に対して大雑把に考えてO(1)です．そのため，どちらを使っても大して変わらないと考えています．最初のコメントにあるように，要素を追加するたびに`_items`を線形検索（O(N)）していて，ほとんど毎回全要素をサーチしていることが，速度が遅いことの原因だからです．

2019-05-03 17:00 UTC, kanreisa commented
まさに
> 似たものが２つあるのはよくない
と考えていますから、提案していただいたパフォーマンス改善の意図をそのまま生かす形で Map 使えたら Map 使ってみましょう

私もテストしますので、ぜひ書き換えてみてください。

2019-05-03 17:02 UTC, kanreisa requested changes

2019-05-03 17:02 UTC, kanreisa commented on src/Mirakurun/Program.ts
> +    private _itemMap: { [programId: number]: ProgramItem } = {};
- Map のほうが良いかもしれないという件
- `_items` の配列は廃止してみましょう

2019-05-04 03:49 UTC, masnagam commented
了解です．念の為，以下の順番でコミットします．

1. `Object` -> `Map`への変更のみ
2. `_items`を削除
3. `_itemMap` -> `_items`に改名

2, 3の修正がまずかったら簡単に戻せるようにしておきます．

2019-05-04 05:23 UTC, masnagam commented
コミットログにも書きましたが，`Map`は[挿入順を記憶している](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Map/entries)みたいです．上手くいけば，`Program.items`の順番は以前と同じはず．．

2019-05-04 08:23 UTC, masnagam commented
`_itemMap`を`_items`に改名すると，名前が似ているものと混同してしまうので止めておきました．

2019-05-04 08:56 UTC, masnagam commented on src/Mirakurun/Program.ts
> +    private _itemMap: { [programId: number]: ProgramItem } = {};
48858b37cf1cd6edfce75e22462440c1605bc80f で削除しました

2019-05-04 08:58 UTC, masnagam commented
単体テストなどがないため，とりあえず暫く動かしてみます

2019-05-05 14:19 UTC, masnagam commented
一日程度動かしましたが，`Map`変更・`_items`削除前と比べて遅くなったりはしていないようでした．

2019-05-11 18:07 UTC, kanreisa requested changes
不要な変更とファイルが混じってしまっているようです

2019-05-12 04:09 UTC, masnagam commented
fbc67e164bbf99118e86d8041796cd02d696158a で行ったDockerfileの変更とdocker-compose.ymlの追加でしょうか？

もしそうであれば fbc67e164bbf99118e86d8041796cd02d696158a をrevertし，別のPRとして出し直します．

2019-05-12 04:13 UTC, masnagam commented
1c7acea08cc448869bfe57a10fc886bfe2159cdb でrevertしました．

Dockerfileの修正とdocker-compose.ymlの追加だったので，revertしても本件の修正には影響を与えません．

2019-05-12 04:55 UTC, masnagam commented
分離して #59 を作成しました．

2019-05-12 13:57 UTC, kanreisa approved these changes

2019-05-12 14:01 UTC, merged

2019-05-12 14:52 UTC, kanreisa commented
ありがとうございます。マージしました。
(https://github.com/Chinachu/Mirakurun/blob/master/CHANGELOG.md