Improve PT2 support
kanreisa/Mirakurun pull request #8
Opened 2016-11-04 14:00 UTC by akimasa

現状ではコマンド起動のすぐ後にSIGTERMを送ることがあり、これがデバイスファイルが使えなくなる現象の原因になるので修正しました。
また、放送波の来ていないチャンネルに合わせると勝手にコマンドが終了して、SIGTERMの送信タイミングとかぶる場合があります。放送波が来ていないチャンネルに合わせると3.5秒ほどで自動終了するので、少し長めの4秒はSIGTERMを送ることがないようにしました。

2016-11-04 14:03 UTC, kanreisa requested changes

2016-11-04 14:03 UTC, kanreisa commented on src/Mirakurun/TunerDevice.ts
> +}
これだけ修正していただければOKです

2016-11-04 23:36 UTC, akimasa commented
Visual Studio Codeを使わずに修正したので、最後がおかしかったですね。
Visual Studio Codeで修正しましたのでご確認ください。

2016-11-05 14:19 UTC, akimasa commented
PT2サポートを利用すると、チャンネル切り替えに数秒かかることがあり、辛いので、緩和策(13ab2c1349479613331d56b3745c017626cb3cd7)を試しています。
せっかくなので一緒にマージしてしまいませんか？
緩和策が有効かどうかと、不具合があるかどうかを確認するため2、3日いただければと思います。
問題なさそうなら、このPRのブランチに入れます。

2016-11-07 23:11 UTC, akimasa commented
手元の環境で確認する限りでは、緩和策は有効で、問題は起こりませんでした。
お手数ですが、コードのレビューをお願いします。

2016-11-10 11:09 UTC, akimasa commented
すみません。
間違えて壊れているソースコードをpushしてしまいました。
c0018c1aaf4c824fdae82e111a1e4e3526328b67 はおそらく壊れています。
revertします。
//確認不足で無駄にコミットを増やしてしまっている…。閉じて綺麗なブランチでやり直した方がいいかな…。

2016-11-16 01:43 UTC, kanreisa requested changes

2016-11-16 01:43 UTC, kanreisa commented on src/Mirakurun/TunerDevice.ts
> +            if (data.toString().match("Recording...")) {
これだと `"Recording..."` が RegExp に変換されて意図しないマッチングも発生します。
match の引数には RegExp を使用するのが良いでしょう。

2016-11-16 01:44 UTC, kanreisa commented on src/Mirakurun/TunerDevice.ts
> +                        this._pt2Resolver = _resolve;
この実装には一抹の不安があります。

2016-11-16 01:44 UTC, kanreisa commented on src/Mirakurun/TunerDevice.ts
> +            if (data.toString().match("Recording...")) {
PT2以外のケースにおいて無駄な処理は省くようにしたいです。

2016-11-16 02:02 UTC, akimasa commented on src/Mirakurun/TunerDevice.ts
> +            if (data.toString().match("Recording...")) {
レビューありがとうございます。
matchの引数の件、了解しました。
PT2以外のケースで無駄な処理を省くというのは、isPT2をチェックしておけば良いのでしょうか。

2016-11-16 02:03 UTC, akimasa commented on src/Mirakurun/TunerDevice.ts
> +                        this._pt2Resolver = _resolve;
よろしければ、もう少し詳しく教えていただけますか？

2016-11-27 14:20 UTC, kanreisa commented on src/Mirakurun/TunerDevice.ts
> +                        this._pt2Resolver = _resolve;
Promiseの解決関数をブロックの外に（ましてやインスタンス全体）漏らすのは今後のコード管理に大きく影響してきます。

2016-12-07 11:01 UTC, akimasa commented
ご指摘の点を直しました。
お手数ですが、ご確認願います。

2016-12-08 17:21 UTC, kanreisa commented
ありがとうございます。
https://github.com/Chinachu/Mirakurun/pull/10
こちらで手直しさせていただきましたので、ご確認ください。
またよろしくお願いいたします 😃

2016-12-08 17:21 UTC, closed without merging

2016-12-09 06:40 UTC, akimasa commented
お手数をおかけしました。
手直しありがとうございます。

放送波の来ていないチャンネルに合わせた場合、終了するタイミングがわからないので、recpt1の終了が被りデバイスファイルが使えなくなる事が確認されました。
Mirakurunでの対策には限界があり、不具合の頻度を落とす事が出来ても完全に防ぐことはできないようです。
次回のリリース告知の際に、この点について書いていただけたらと思います。
PT2サポートと聞いて、isPT2をtrueにすれば安心だと思われたら困りますので…

2016-12-09 09:54 UTC, kanreisa commented
なるほどそれでは本機能をドロップしてしまうことといたしましょう